# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BindingType(str, Enum):
    """
    The type of binding for the image build.
    """

    """
    allowed enum values
    """
    BindingTypeEarly = 'early'
    BindingTypeLate = 'late'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BindingType from a JSON string"""
        return cls(json.loads(json_str))


