# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExistingCatalogItemTarget(BaseModel):
    """
    Publish target that appends a version to an existing CatalogItem. Rejected immediately if the CatalogItem does not exist.
    """ # noqa: E501
    type: StrictStr = Field(description="Discriminator for the target type.")
    catalog_name: StrictStr = Field(description="Name of the parent Catalog resource.", alias="catalogName")
    catalog_item_name: StrictStr = Field(description="Name of the CatalogItem to update.", alias="catalogItemName")
    version: StrictStr = Field(description="Semver version string for the new CatalogItem version entry.")
    readme: Optional[StrictStr] = Field(default=None, description="Optional version-level readme for this version entry. Markdown is supported.")
    replaces: Optional[StrictStr] = Field(default=None, description="The single version this one replaces, defining the primary upgrade edge.")
    skips: Optional[List[StrictStr]] = Field(default=None, description="Additional versions that can upgrade directly to this one.")
    skip_range: Optional[StrictStr] = Field(default=None, description="Semver range of versions that can upgrade directly to this one (e.g. \">=1.0.0 <1.3.0\").", alias="skipRange")
    __properties: ClassVar[List[str]] = ["type", "catalogName", "catalogItemName", "version", "readme", "replaces", "skips", "skipRange"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ExistingCatalogItem']):
            raise ValueError("must be one of enum values ('ExistingCatalogItem')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExistingCatalogItemTarget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExistingCatalogItemTarget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "catalogName": obj.get("catalogName"),
            "catalogItemName": obj.get("catalogItemName"),
            "version": obj.get("version"),
            "readme": obj.get("readme"),
            "replaces": obj.get("replaces"),
            "skips": obj.get("skips"),
            "skipRange": obj.get("skipRange")
        })
        return _obj


