# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExportFormatType(str, Enum):
    """
    The type of format to export the image to.
    """

    """
    allowed enum values
    """
    ExportFormatTypeVMDK = 'vmdk'
    ExportFormatTypeQCOW2 = 'qcow2'
    ExportFormatTypeISO = 'iso'
    ExportFormatTypeQCOW2DiskContainer = 'qcow2-disk-container'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExportFormatType from a JSON string"""
        return cls(json.loads(json_str))


