# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from flightctl.imagebuilder.models.api_version import ApiVersion
from flightctl.imagebuilder.models.image_build_spec import ImageBuildSpec
from flightctl.imagebuilder.models.image_build_status import ImageBuildStatus
from flightctl.imagebuilder.models.image_export import ImageExport
from flightctl.imagebuilder.models.object_meta import ObjectMeta
from typing import Optional, Set
from typing_extensions import Self

class ImageBuild(BaseModel):
    """
    ImageBuild represents a build request for a container image.
    """ # noqa: E501
    api_version: ApiVersion = Field(alias="apiVersion")
    kind: StrictStr = Field(description="Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.")
    metadata: ObjectMeta
    spec: ImageBuildSpec
    status: Optional[ImageBuildStatus] = None
    imageexports: Optional[List[ImageExport]] = Field(default=None, description="Array of ImageExport resources that reference this ImageBuild. Only populated when withExports query parameter is true.")
    __properties: ClassVar[List[str]] = ["apiVersion", "kind", "metadata", "spec", "status", "imageexports"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageBuild from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spec
        if self.spec:
            _dict['spec'] = self.spec.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in imageexports (list)
        _items = []
        if self.imageexports:
            for _item_imageexports in self.imageexports:
                if _item_imageexports:
                    _items.append(_item_imageexports.to_dict())
            _dict['imageexports'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageBuild from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "kind": obj.get("kind"),
            "metadata": ObjectMeta.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "spec": ImageBuildSpec.from_dict(obj["spec"]) if obj.get("spec") is not None else None,
            "status": ImageBuildStatus.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "imageexports": [ImageExport.from_dict(_item) for _item in obj["imageexports"]] if obj.get("imageexports") is not None else None
        })
        return _obj


