# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.api.imagepromotion_api import ImagepromotionApi


class TestImagepromotionApi(unittest.TestCase):
    """ImagepromotionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagepromotionApi()

    def tearDown(self) -> None:
        pass

    def test_create_image_promotion(self) -> None:
        """Test case for create_image_promotion

        """
        pass

    def test_delete_image_promotion(self) -> None:
        """Test case for delete_image_promotion

        """
        pass

    def test_get_image_promotion(self) -> None:
        """Test case for get_image_promotion

        """
        pass

    def test_list_image_promotions(self) -> None:
        """Test case for list_image_promotions

        """
        pass

    def test_patch_image_promotion(self) -> None:
        """Test case for patch_image_promotion

        """
        pass

    def test_replace_image_promotion(self) -> None:
        """Test case for replace_image_promotion

        """
        pass


if __name__ == '__main__':
    unittest.main()
