# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_promotion_condition_reason import ImagePromotionConditionReason

class TestImagePromotionConditionReason(unittest.TestCase):
    """ImagePromotionConditionReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImagePromotionConditionReason(self):
        """Test ImagePromotionConditionReason"""
        # inst = ImagePromotionConditionReason()

if __name__ == '__main__':
    unittest.main()
