# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_build_condition_reason import ImageBuildConditionReason

class TestImageBuildConditionReason(unittest.TestCase):
    """ImageBuildConditionReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageBuildConditionReason(self):
        """Test ImageBuildConditionReason"""
        # inst = ImageBuildConditionReason()

if __name__ == '__main__':
    unittest.main()
