# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_export_condition_type import ImageExportConditionType

class TestImageExportConditionType(unittest.TestCase):
    """ImageExportConditionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageExportConditionType(self):
        """Test ImageExportConditionType"""
        # inst = ImageExportConditionType()

if __name__ == '__main__':
    unittest.main()
