# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_build import ImageBuild

class TestImageBuild(unittest.TestCase):
    """ImageBuild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageBuild:
        """Test ImageBuild
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageBuild`
        """
        model = ImageBuild()
        if include_optional:
            return ImageBuild(
                api_version = 'v1alpha1',
                kind = '',
                metadata = flightctl.imagebuilder.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = flightctl.imagebuilder.models.image_build_spec.ImageBuildSpec(
                    source = flightctl.imagebuilder.models.image_build_source.ImageBuildSource(
                        repository = '', 
                        image_name = '', 
                        image_tag = '', ), 
                    destination = flightctl.imagebuilder.models.image_build_destination.ImageBuildDestination(
                        repository = '', 
                        image_name = '', 
                        image_tag = '', ), 
                    binding = null, 
                    user_configuration = flightctl.imagebuilder.models.image_build_user_configuration.ImageBuildUserConfiguration(
                        username = '', 
                        publickey = '', ), ),
                status = flightctl.imagebuilder.models.image_build_status.ImageBuildStatus(
                    conditions = [
                        null
                        ], 
                    image_reference = '', 
                    architecture = '', 
                    manifest_digest = '', 
                    last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                imageexports = [
                    flightctl.imagebuilder.models.image_export.ImageExport(
                        api_version = 'v1alpha1', 
                        kind = '', 
                        metadata = flightctl.imagebuilder.models.object_meta.ObjectMeta(
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            name = '', 
                            labels = {
                                'key' : ''
                                }, 
                            generation = 56, 
                            owner = '', 
                            annotations = {
                                'key' : ''
                                }, 
                            resource_version = '', ), 
                        spec = flightctl.imagebuilder.models.image_export_spec.ImageExportSpec(
                            source = flightctl.imagebuilder.models.image_build_ref_source.ImageBuildRefSource(
                                type = 'imageBuild', 
                                image_build_ref = '', ), 
                            format = 'vmdk', ), 
                        status = flightctl.imagebuilder.models.image_export_status.ImageExportStatus(
                            conditions = [
                                null
                                ], 
                            manifest_digest = '', 
                            last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ]
            )
        else:
            return ImageBuild(
                api_version = 'v1alpha1',
                kind = '',
                metadata = flightctl.imagebuilder.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = flightctl.imagebuilder.models.image_build_spec.ImageBuildSpec(
                    source = flightctl.imagebuilder.models.image_build_source.ImageBuildSource(
                        repository = '', 
                        image_name = '', 
                        image_tag = '', ), 
                    destination = flightctl.imagebuilder.models.image_build_destination.ImageBuildDestination(
                        repository = '', 
                        image_name = '', 
                        image_tag = '', ), 
                    binding = null, 
                    user_configuration = flightctl.imagebuilder.models.image_build_user_configuration.ImageBuildUserConfiguration(
                        username = '', 
                        publickey = '', ), ),
        )
        """

    def testImageBuild(self):
        """Test ImageBuild"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
