# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_promotion_target import ImagePromotionTarget

class TestImagePromotionTarget(unittest.TestCase):
    """ImagePromotionTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImagePromotionTarget:
        """Test ImagePromotionTarget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImagePromotionTarget`
        """
        model = ImagePromotionTarget()
        if include_optional:
            return ImagePromotionTarget(
                type = 'NewCatalogItem',
                catalog_name = '',
                catalog_item_name = '',
                version = '',
                readme = '',
                display_name = '',
                replaces = '',
                skips = [
                    ''
                    ],
                skip_range = ''
            )
        else:
            return ImagePromotionTarget(
                type = 'NewCatalogItem',
                catalog_name = '',
                catalog_item_name = '',
                version = '',
        )
        """

    def testImagePromotionTarget(self):
        """Test ImagePromotionTarget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
