# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_promotion import ImagePromotion

class TestImagePromotion(unittest.TestCase):
    """ImagePromotion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImagePromotion:
        """Test ImagePromotion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImagePromotion`
        """
        model = ImagePromotion()
        if include_optional:
            return ImagePromotion(
                api_version = 'v1alpha1',
                kind = '',
                metadata = flightctl.imagebuilder.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = flightctl.imagebuilder.models.image_promotion_spec.ImagePromotionSpec(
                    source = flightctl.imagebuilder.models.image_promotion_source.ImagePromotionSource(
                        image_build_ref = '0', 
                        export_formats = [
                            'vmdk'
                            ], ), 
                    target = null, ),
                status = flightctl.imagebuilder.models.image_promotion_status.ImagePromotionStatus(
                    conditions = [
                        null
                        ], 
                    published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_amended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    artifact_statuses = [
                        flightctl.imagebuilder.models.artifact_promotion_status.ArtifactPromotionStatus(
                            format = '', 
                            ready = True, 
                            published = True, 
                            resolved_export = '', )
                        ], )
            )
        else:
            return ImagePromotion(
                api_version = 'v1alpha1',
                kind = '',
                metadata = flightctl.imagebuilder.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = flightctl.imagebuilder.models.image_promotion_spec.ImagePromotionSpec(
                    source = flightctl.imagebuilder.models.image_promotion_source.ImagePromotionSource(
                        image_build_ref = '0', 
                        export_formats = [
                            'vmdk'
                            ], ), 
                    target = null, ),
        )
        """

    def testImagePromotion(self):
        """Test ImagePromotion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
