# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.models.image_build_source import ImageBuildSource

class TestImageBuildSource(unittest.TestCase):
    """ImageBuildSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageBuildSource:
        """Test ImageBuildSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageBuildSource`
        """
        model = ImageBuildSource()
        if include_optional:
            return ImageBuildSource(
                repository = '',
                image_name = '',
                image_tag = ''
            )
        else:
            return ImageBuildSource(
                repository = '',
                image_name = '',
                image_tag = '',
        )
        """

    def testImageBuildSource(self):
        """Test ImageBuildSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
