# coding: utf-8

"""
    Flight Control Image Builder API

    Image Builder service for Flight Control. This service manages image build resources for building and pushing container images. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.imagebuilder.api.imagebuild_api import ImagebuildApi


class TestImagebuildApi(unittest.TestCase):
    """ImagebuildApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagebuildApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_image_build(self) -> None:
        """Test case for cancel_image_build

        """
        pass

    def test_create_image_build(self) -> None:
        """Test case for create_image_build

        """
        pass

    def test_delete_image_build(self) -> None:
        """Test case for delete_image_build

        """
        pass

    def test_get_image_build(self) -> None:
        """Test case for get_image_build

        """
        pass

    def test_get_image_build_log(self) -> None:
        """Test case for get_image_build_log

        """
        pass

    def test_list_image_builds(self) -> None:
        """Test case for list_image_builds

        """
        pass


if __name__ == '__main__':
    unittest.main()
