# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.device_updated_status_type import DeviceUpdatedStatusType

class TestDeviceUpdatedStatusType(unittest.TestCase):
    """DeviceUpdatedStatusType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceUpdatedStatusType(self):
        """Test DeviceUpdatedStatusType"""
        # inst = DeviceUpdatedStatusType()

if __name__ == '__main__':
    unittest.main()
