# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.container_application import ContainerApplication

class TestContainerApplication(unittest.TestCase):
    """ContainerApplication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContainerApplication:
        """Test ContainerApplication
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContainerApplication`
        """
        model = ContainerApplication()
        if include_optional:
            return ContainerApplication(
                name = '',
                app_type = 'compose',
                env_vars = {
                    'key' : ''
                    },
                run_as = '',
                volumes = [
                    null
                    ],
                image = '',
                ports = [
                    '8080:80'
                    ],
                resources = flightctl.models.application_resources.ApplicationResources(
                    limits = flightctl.models.application_resource_limits.ApplicationResourceLimits(
                        cpu = '0.75', 
                        memory = '256m', ), )
            )
        else:
            return ContainerApplication(
                app_type = 'compose',
                image = '',
        )
        """

    def testContainerApplication(self):
        """Test ContainerApplication"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
