# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.resource_alert_severity_type import ResourceAlertSeverityType

class TestResourceAlertSeverityType(unittest.TestCase):
    """ResourceAlertSeverityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceAlertSeverityType(self):
        """Test ResourceAlertSeverityType"""
        # inst = ResourceAlertSeverityType()

if __name__ == '__main__':
    unittest.main()
