# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.rollout_policy import RolloutPolicy

class TestRolloutPolicy(unittest.TestCase):
    """RolloutPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RolloutPolicy:
        """Test RolloutPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RolloutPolicy`
        """
        model = RolloutPolicy()
        if include_optional:
            return RolloutPolicy(
                disruption_budget = flightctl.models.disruption_budget.DisruptionBudget(
                    group_by = [
                        'C98JLe5iL60-aa-.Ctq9dcsc.2-790gAa7Xa5u50ArrlGpCQjkQVRmfnjddwcDM.9fv7'
                        ], 
                    min_available = 1, 
                    max_unavailable = 1, ),
                device_selection = flightctl.models.rollout_device_selection.RolloutDeviceSelection(),
                success_threshold = '',
                default_update_timeout = '0s'
            )
        else:
            return RolloutPolicy(
        )
        """

    def testRolloutPolicy(self):
        """Test RolloutPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
