# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.open_shift_provider_spec import OpenShiftProviderSpec

class TestOpenShiftProviderSpec(unittest.TestCase):
    """OpenShiftProviderSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenShiftProviderSpec:
        """Test OpenShiftProviderSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenShiftProviderSpec`
        """
        model = OpenShiftProviderSpec()
        if include_optional:
            return OpenShiftProviderSpec(
                provider_type = 'openshift',
                display_name = '',
                issuer = '',
                authorization_url = '',
                token_url = '',
                client_id = '',
                client_secret = '',
                enabled = True,
                scopes = [
                    ''
                    ],
                cluster_control_plane_url = '',
                project_label_filter = '',
                role_suffix = ''
            )
        else:
            return OpenShiftProviderSpec(
                provider_type = 'openshift',
        )
        """

    def testOpenShiftProviderSpec(self):
        """Test OpenShiftProviderSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
