# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.api.certificatesigningrequest_api import CertificatesigningrequestApi


class TestCertificatesigningrequestApi(unittest.TestCase):
    """CertificatesigningrequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CertificatesigningrequestApi()

    def tearDown(self) -> None:
        pass

    def test_create_certificate_signing_request(self) -> None:
        """Test case for create_certificate_signing_request

        """
        pass

    def test_delete_certificate_signing_request(self) -> None:
        """Test case for delete_certificate_signing_request

        """
        pass

    def test_delete_certificate_signing_requests(self) -> None:
        """Test case for delete_certificate_signing_requests

        """
        pass

    def test_list_certificate_signing_requests(self) -> None:
        """Test case for list_certificate_signing_requests

        """
        pass

    def test_patch_certificate_signing_request(self) -> None:
        """Test case for patch_certificate_signing_request

        """
        pass

    def test_read_certificate_signing_request(self) -> None:
        """Test case for read_certificate_signing_request

        """
        pass

    def test_replace_certificate_signing_request(self) -> None:
        """Test case for replace_certificate_signing_request

        """
        pass

    def test_update_certificate_signing_request_approval(self) -> None:
        """Test case for update_certificate_signing_request_approval

        """
        pass


if __name__ == '__main__':
    unittest.main()
