# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.systemd_unit_status import SystemdUnitStatus

class TestSystemdUnitStatus(unittest.TestCase):
    """SystemdUnitStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemdUnitStatus:
        """Test SystemdUnitStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemdUnitStatus`
        """
        model = SystemdUnitStatus()
        if include_optional:
            return SystemdUnitStatus(
                unit = 'sshd.service',
                description = 'OpenSSH server daemon',
                enable_state = 'enabled',
                load_state = 'stub',
                active_state = 'active',
                sub_state = 'running'
            )
        else:
            return SystemdUnitStatus(
                unit = 'sshd.service',
                description = 'OpenSSH server daemon',
                enable_state = 'enabled',
                load_state = 'stub',
                active_state = 'active',
                sub_state = 'running',
        )
        """

    def testSystemdUnitStatus(self):
        """Test SystemdUnitStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
