# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.oci_repo_spec import OciRepoSpec

class TestOciRepoSpec(unittest.TestCase):
    """OciRepoSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OciRepoSpec:
        """Test OciRepoSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OciRepoSpec`
        """
        model = OciRepoSpec()
        if include_optional:
            return OciRepoSpec(
                registry = '',
                scheme = 'https',
                type = 'oci',
                access_mode = 'Read',
                oci_auth = flightctl.models.docker_auth.DockerAuth(
                    auth_type = 'docker', 
                    username = '', 
                    password = '', ),
                ca_crt = '',
                skip_server_verification = True
            )
        else:
            return OciRepoSpec(
                registry = '',
                type = 'oci',
        )
        """

    def testOciRepoSpec(self):
        """Test OciRepoSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
