# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.api_version import ApiVersion

class TestApiVersion(unittest.TestCase):
    """ApiVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiVersion(self):
        """Test ApiVersion"""
        # inst = ApiVersion()

if __name__ == '__main__':
    unittest.main()
