# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.internal_task_failed_details import InternalTaskFailedDetails

class TestInternalTaskFailedDetails(unittest.TestCase):
    """InternalTaskFailedDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalTaskFailedDetails:
        """Test InternalTaskFailedDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalTaskFailedDetails`
        """
        model = InternalTaskFailedDetails()
        if include_optional:
            return InternalTaskFailedDetails(
                detail_type = 'InternalTaskFailed',
                error_message = '',
                retry_count = 56,
                original_event = flightctl.models.event.Event(
                    api_version = '', 
                    kind = '', 
                    metadata = flightctl.models.object_meta.ObjectMeta(
                        creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        labels = {
                            'key' : ''
                            }, 
                        generation = 56, 
                        owner = '', 
                        annotations = {
                            'key' : ''
                            }, 
                        resource_version = '', ), 
                    involved_object = flightctl.models.object_reference.ObjectReference(
                        kind = '', 
                        name = '', ), 
                    reason = 'ResourceCreated', 
                    message = '', 
                    details = flightctl.models.event_details.EventDetails(), 
                    type = 'Normal', 
                    source = flightctl.models.event_source.EventSource(
                        component = '', ), 
                    actor = '', )
            )
        else:
            return InternalTaskFailedDetails(
                detail_type = 'InternalTaskFailed',
                error_message = '',
                original_event = flightctl.models.event.Event(
                    api_version = '', 
                    kind = '', 
                    metadata = flightctl.models.object_meta.ObjectMeta(
                        creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        labels = {
                            'key' : ''
                            }, 
                        generation = 56, 
                        owner = '', 
                        annotations = {
                            'key' : ''
                            }, 
                        resource_version = '', ), 
                    involved_object = flightctl.models.object_reference.ObjectReference(
                        kind = '', 
                        name = '', ), 
                    reason = 'ResourceCreated', 
                    message = '', 
                    details = flightctl.models.event_details.EventDetails(), 
                    type = 'Normal', 
                    source = flightctl.models.event_source.EventSource(
                        component = '', ), 
                    actor = '', ),
        )
        """

    def testInternalTaskFailedDetails(self):
        """Test InternalTaskFailedDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
