# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.k8s_provider_spec import K8sProviderSpec

class TestK8sProviderSpec(unittest.TestCase):
    """K8sProviderSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> K8sProviderSpec:
        """Test K8sProviderSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `K8sProviderSpec`
        """
        model = K8sProviderSpec()
        if include_optional:
            return K8sProviderSpec(
                provider_type = 'k8s',
                display_name = '',
                api_url = '',
                rbac_ns = '',
                enabled = True,
                organization_assignment = flightctl.models.auth_organization_assignment.AuthOrganizationAssignment(),
                role_assignment = flightctl.models.auth_role_assignment.AuthRoleAssignment(),
                role_suffix = ''
            )
        else:
            return K8sProviderSpec(
                provider_type = 'k8s',
                api_url = '',
                organization_assignment = flightctl.models.auth_organization_assignment.AuthOrganizationAssignment(),
                role_assignment = flightctl.models.auth_role_assignment.AuthRoleAssignment(),
        )
        """

    def testK8sProviderSpec(self):
        """Test K8sProviderSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
