# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.device_spec import DeviceSpec

class TestDeviceSpec(unittest.TestCase):
    """DeviceSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceSpec:
        """Test DeviceSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceSpec`
        """
        model = DeviceSpec()
        if include_optional:
            return DeviceSpec(
                update_policy = flightctl.models.device_update_policy_spec.DeviceUpdatePolicySpec(
                    download_schedule = flightctl.models.update_schedule.UpdateSchedule(
                        time_zone = 'Local', 
                        at = '', 
                        start_grace_duration = '0s', ), 
                    update_schedule = flightctl.models.update_schedule.UpdateSchedule(
                        time_zone = 'Local', 
                        at = '', 
                        start_grace_duration = '0s', ), ),
                os = flightctl.models.device_os_spec.DeviceOsSpec(
                    image = '', ),
                config = [
                    null
                    ],
                applications = [
                    flightctl.models.application_provider_spec.ApplicationProviderSpec()
                    ],
                systemd = flightctl.models.device_spec_systemd.DeviceSpec_systemd(
                    match_patterns = [
                        'ge34w9Wa*CLfoo\\yJX2gCb'
                        ], ),
                resources = [
                    null
                    ],
                consoles = [
                    flightctl.models.device_console.DeviceConsole(
                        session_metadata = '', 
                        session_id = '', )
                    ],
                decommissioning = flightctl.models.device_decommission.DeviceDecommission(
                    target = 'Unenroll', )
            )
        else:
            return DeviceSpec(
        )
        """

    def testDeviceSpec(self):
        """Test DeviceSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
