# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.condition_type import ConditionType

class TestConditionType(unittest.TestCase):
    """ConditionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionType(self):
        """Test ConditionType"""
        # inst = ConditionType()

if __name__ == '__main__':
    unittest.main()
