# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.api.labels_api import LabelsApi


class TestLabelsApi(unittest.TestCase):
    """LabelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LabelsApi()

    def tearDown(self) -> None:
        pass

    def test_list_labels(self) -> None:
        """Test case for list_labels

        """
        pass


if __name__ == '__main__':
    unittest.main()
