# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.catalog_item_ref_application_provider_spec import CatalogItemRefApplicationProviderSpec

class TestCatalogItemRefApplicationProviderSpec(unittest.TestCase):
    """CatalogItemRefApplicationProviderSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogItemRefApplicationProviderSpec:
        """Test CatalogItemRefApplicationProviderSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogItemRefApplicationProviderSpec`
        """
        model = CatalogItemRefApplicationProviderSpec()
        if include_optional:
            return CatalogItemRefApplicationProviderSpec(
                catalog_item_ref = flightctl.models.catalog_item_ref_spec.CatalogItemRefSpec(
                    catalog = '', 
                    item = '', 
                    version = '', 
                    channel = '', )
            )
        else:
            return CatalogItemRefApplicationProviderSpec(
                catalog_item_ref = flightctl.models.catalog_item_ref_spec.CatalogItemRefSpec(
                    catalog = '', 
                    item = '', 
                    version = '', 
                    channel = '', ),
        )
        """

    def testCatalogItemRefApplicationProviderSpec(self):
        """Test CatalogItemRefApplicationProviderSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
