# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.models.auth_provider_spec import AuthProviderSpec

class TestAuthProviderSpec(unittest.TestCase):
    """AuthProviderSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthProviderSpec:
        """Test AuthProviderSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthProviderSpec`
        """
        model = AuthProviderSpec()
        if include_optional:
            return AuthProviderSpec(
                provider_type = 'k8s',
                display_name = '',
                issuer = '',
                client_id = '',
                client_secret = '',
                enabled = True,
                scopes = [
                    ''
                    ],
                organization_assignment = flightctl.models.auth_organization_assignment.AuthOrganizationAssignment(),
                username_claim = [
                    ''
                    ],
                role_assignment = flightctl.models.auth_role_assignment.AuthRoleAssignment(),
                authorization_url = '',
                token_url = '',
                userinfo_url = '',
                introspection = flightctl.models.o_auth2_introspection.OAuth2Introspection(),
                cluster_control_plane_url = '',
                project_label_filter = '',
                role_suffix = '',
                api_url = '',
                rbac_ns = ''
            )
        else:
            return AuthProviderSpec(
                provider_type = 'k8s',
                issuer = '',
                client_id = '',
                client_secret = '',
                scopes = [
                    ''
                    ],
                organization_assignment = flightctl.models.auth_organization_assignment.AuthOrganizationAssignment(),
                role_assignment = flightctl.models.auth_role_assignment.AuthRoleAssignment(),
                authorization_url = '',
                token_url = '',
                userinfo_url = '',
                api_url = '',
        )
        """

    def testAuthProviderSpec(self):
        """Test AuthProviderSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
