# coding: utf-8

# flake8: noqa
"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads.  This API version (v1alpha1) contains alpha-stage resources that are subject to change. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from flightctl.v1alpha1.models.api_version import ApiVersion
from flightctl.v1alpha1.models.catalog import Catalog
from flightctl.v1alpha1.models.catalog_item import CatalogItem
from flightctl.v1alpha1.models.catalog_item_artifact import CatalogItemArtifact
from flightctl.v1alpha1.models.catalog_item_artifact_type import CatalogItemArtifactType
from flightctl.v1alpha1.models.catalog_item_category import CatalogItemCategory
from flightctl.v1alpha1.models.catalog_item_configurable import CatalogItemConfigurable
from flightctl.v1alpha1.models.catalog_item_deprecation import CatalogItemDeprecation
from flightctl.v1alpha1.models.catalog_item_list import CatalogItemList
from flightctl.v1alpha1.models.catalog_item_meta import CatalogItemMeta
from flightctl.v1alpha1.models.catalog_item_spec import CatalogItemSpec
from flightctl.v1alpha1.models.catalog_item_type import CatalogItemType
from flightctl.v1alpha1.models.catalog_item_version import CatalogItemVersion
from flightctl.v1alpha1.models.catalog_list import CatalogList
from flightctl.v1alpha1.models.catalog_spec import CatalogSpec
from flightctl.v1alpha1.models.catalog_status import CatalogStatus
from flightctl.v1alpha1.models.condition import Condition
from flightctl.v1alpha1.models.condition_base import ConditionBase
from flightctl.v1alpha1.models.condition_status import ConditionStatus
from flightctl.v1alpha1.models.condition_type import ConditionType
from flightctl.v1alpha1.models.list_meta import ListMeta
from flightctl.v1alpha1.models.object_meta import ObjectMeta
from flightctl.v1alpha1.models.patch_request_inner import PatchRequestInner
from flightctl.v1alpha1.models.schemas_api_version import SchemasApiVersion
from flightctl.v1alpha1.models.schemas_status import SchemasStatus
from flightctl.v1alpha1.models.status import Status

