# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads.  This API version (v1alpha1) contains alpha-stage resources that are subject to change. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from flightctl.v1alpha1.models.vulnerability_group_item import VulnerabilityGroupItem
from typing import Optional, Set
from typing_extensions import Self

class AffectedFleet(BaseModel):
    """
    One fleet or the fleetless aggregate with device and image counts for a CVE.
    """ # noqa: E501
    fleet_name: StrictStr = Field(description="Fleet metadata.name, empty for the fleetless aggregate.", alias="fleetName")
    fleetless: StrictBool = Field(description="True when this row represents devices not owned by a fleet.")
    affected_devices: StrictInt = Field(description="Devices in this fleet or fleetless group affected by the CVE.", alias="affectedDevices")
    findings: List[VulnerabilityGroupItem] = Field(description="Per-digest findings within this fleet or fleetless group.")
    __properties: ClassVar[List[str]] = ["fleetName", "fleetless", "affectedDevices", "findings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AffectedFleet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in findings (list)
        _items = []
        if self.findings:
            for _item_findings in self.findings:
                if _item_findings:
                    _items.append(_item_findings.to_dict())
            _dict['findings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AffectedFleet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fleetName": obj.get("fleetName"),
            "fleetless": obj.get("fleetless"),
            "affectedDevices": obj.get("affectedDevices"),
            "findings": [VulnerabilityGroupItem.from_dict(_item) for _item in obj["findings"]] if obj.get("findings") is not None else None
        })
        return _obj


