# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads.  This API version (v1alpha1) contains alpha-stage resources that are subject to change. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from flightctl.v1alpha1.models.api_version import ApiVersion
from flightctl.v1alpha1.models.catalog_item_deployment_deployed_to import CatalogItemDeploymentDeployedTo
from typing import Optional, Set
from typing_extensions import Self

class CatalogItemDeployment(BaseModel):
    """
    CatalogItemDeployment represents a specific deployment of a catalog item to a fleet or device. A catalog item associated to a fleet that has no devices is still considered a deployment. A deployment is only associated with the fleet and not the individual devices in cases where a device is using a catalog item deployment that came from a device spec template on a fleet.
    """ # noqa: E501
    api_version: ApiVersion = Field(alias="apiVersion")
    kind: StrictStr = Field(description="Kind is a string value representing the REST resource this object represents.")
    deployed_to: Optional[CatalogItemDeploymentDeployedTo] = Field(default=None, alias="deployedTo")
    catalog: StrictStr = Field(description="The catalog of the catalogItem.")
    catalog_item: StrictStr = Field(description="The catalogItem that this deployment corresponds to.", alias="catalogItem")
    version: StrictStr = Field(description="The version of the catalog item that is deployed.")
    channel: Optional[StrictStr] = Field(default=None, description="The channel, if any, that is intended to be tracked for the catalog item.")
    application_name: Optional[StrictStr] = Field(default=None, description="For catalog items in the 'application' category, the name of the application on the device that the deployment is associated with. Required for application catalog items.", alias="applicationName")
    __properties: ClassVar[List[str]] = ["apiVersion", "kind", "deployedTo", "catalog", "catalogItem", "version", "channel", "applicationName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CatalogItemDeployment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deployed_to
        if self.deployed_to:
            _dict['deployedTo'] = self.deployed_to.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CatalogItemDeployment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "kind": obj.get("kind"),
            "deployedTo": CatalogItemDeploymentDeployedTo.from_dict(obj["deployedTo"]) if obj.get("deployedTo") is not None else None,
            "catalog": obj.get("catalog"),
            "catalogItem": obj.get("catalogItem"),
            "version": obj.get("version"),
            "channel": obj.get("channel"),
            "applicationName": obj.get("applicationName")
        })
        return _obj


