# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads.  This API version (v1alpha1) contains alpha-stage resources that are subject to change. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.v1alpha1.api.catalog_api import CatalogApi


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogApi()

    def tearDown(self) -> None:
        pass

    def test_create_catalog(self) -> None:
        """Test case for create_catalog

        """
        pass

    def test_create_catalog_item(self) -> None:
        """Test case for create_catalog_item

        """
        pass

    def test_delete_catalog(self) -> None:
        """Test case for delete_catalog

        """
        pass

    def test_delete_catalog_item(self) -> None:
        """Test case for delete_catalog_item

        """
        pass

    def test_get_catalog(self) -> None:
        """Test case for get_catalog

        """
        pass

    def test_get_catalog_item(self) -> None:
        """Test case for get_catalog_item

        """
        pass

    def test_get_catalog_status(self) -> None:
        """Test case for get_catalog_status

        """
        pass

    def test_list_all_catalog_items(self) -> None:
        """Test case for list_all_catalog_items

        """
        pass

    def test_list_catalog_items(self) -> None:
        """Test case for list_catalog_items

        """
        pass

    def test_list_catalogs(self) -> None:
        """Test case for list_catalogs

        """
        pass

    def test_patch_catalog(self) -> None:
        """Test case for patch_catalog

        """
        pass

    def test_patch_catalog_item(self) -> None:
        """Test case for patch_catalog_item

        """
        pass

    def test_patch_catalog_status(self) -> None:
        """Test case for patch_catalog_status

        """
        pass

    def test_replace_catalog(self) -> None:
        """Test case for replace_catalog

        """
        pass

    def test_replace_catalog_item(self) -> None:
        """Test case for replace_catalog_item

        """
        pass

    def test_replace_catalog_status(self) -> None:
        """Test case for replace_catalog_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
