# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads.  This API version (v1alpha1) contains alpha-stage resources that are subject to change. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.v1alpha1.models.catalog_status import CatalogStatus

class TestCatalogStatus(unittest.TestCase):
    """CatalogStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogStatus:
        """Test CatalogStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogStatus`
        """
        model = CatalogStatus()
        if include_optional:
            return CatalogStatus(
                conditions = [
                    null
                    ]
            )
        else:
            return CatalogStatus(
                conditions = [
                    null
                    ],
        )
        """

    def testCatalogStatus(self):
        """Test CatalogStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
