# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads.  This API version (v1alpha1) contains alpha-stage resources that are subject to change. 

    The version of the OpenAPI document: v1alpha1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flightctl.v1alpha1.models.catalog import Catalog

class TestCatalog(unittest.TestCase):
    """Catalog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Catalog:
        """Test Catalog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Catalog`
        """
        model = Catalog()
        if include_optional:
            return Catalog(
                api_version = 'v1alpha1',
                kind = '',
                metadata = flightctl.v1alpha1.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = flightctl.v1alpha1.models.catalog_spec.CatalogSpec(
                    display_name = '', 
                    short_description = '', 
                    icon = '', 
                    provider = '', 
                    support = '', ),
                status = flightctl.v1alpha1.models.catalog_status.CatalogStatus(
                    conditions = [
                        null
                        ], )
            )
        else:
            return Catalog(
                api_version = 'v1alpha1',
                kind = '',
                metadata = flightctl.v1alpha1.models.object_meta.ObjectMeta(
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    labels = {
                        'key' : ''
                        }, 
                    generation = 56, 
                    owner = '', 
                    annotations = {
                        'key' : ''
                        }, 
                    resource_version = '', ),
                spec = flightctl.v1alpha1.models.catalog_spec.CatalogSpec(
                    display_name = '', 
                    short_description = '', 
                    icon = '', 
                    provider = '', 
                    support = '', ),
        )
        """

    def testCatalog(self):
        """Test Catalog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
