# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JwtIntrospectionSpec(BaseModel):
    """
    JwtIntrospectionSpec defines token introspection using JWT validation with JWKS.
    """ # noqa: E501
    type: StrictStr = Field(description="The introspection type.")
    jwks_url: StrictStr = Field(description="The JWKS (JSON Web Key Set) endpoint URL for fetching public keys to validate JWT signatures.", alias="jwksUrl")
    issuer: Optional[StrictStr] = Field(default=None, description="Expected issuer claim value in the JWT. If not specified, uses the OAuth2ProviderSpec issuer.")
    audience: Optional[List[StrictStr]] = Field(default=None, description="Expected audience claim values in the JWT. If not specified, uses the OAuth2ProviderSpec clientId.")
    __properties: ClassVar[List[str]] = ["type", "jwksUrl", "issuer", "audience"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['jwt']):
            raise ValueError("must be one of enum values ('jwt')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JwtIntrospectionSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JwtIntrospectionSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "jwksUrl": obj.get("jwksUrl"),
            "issuer": obj.get("issuer"),
            "audience": obj.get("audience")
        })
        return _obj


