# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from flightctl.models.auth_organization_assignment import AuthOrganizationAssignment
from flightctl.models.auth_role_assignment import AuthRoleAssignment
from typing import Optional, Set
from typing_extensions import Self

class K8sProviderSpec(BaseModel):
    """
    K8sProviderSpec describes a Kubernetes/OpenShift provider configuration.
    """ # noqa: E501
    provider_type: StrictStr = Field(description="The type of authentication provider.", alias="providerType")
    display_name: Optional[StrictStr] = Field(default=None, description="Human-readable display name for the provider.", alias="displayName")
    api_url: StrictStr = Field(description="The internal Kubernetes API URL.", alias="apiUrl")
    rbac_ns: Optional[StrictStr] = Field(default=None, description="The RBAC namespace for permissions.", alias="rbacNs")
    enabled: Optional[StrictBool] = Field(default=True, description="Whether this K8s provider is enabled.")
    organization_assignment: AuthOrganizationAssignment = Field(alias="organizationAssignment")
    role_assignment: AuthRoleAssignment = Field(alias="roleAssignment")
    role_suffix: Optional[StrictStr] = Field(default=None, description="Optional suffix to strip from ClusterRole names when normalizing role names. Used for multi-release deployments where ClusterRoles have namespace-specific names (e.g., flightctl-admin-<namespace>).", alias="roleSuffix")
    __properties: ClassVar[List[str]] = ["providerType", "displayName", "apiUrl", "rbacNs", "enabled", "organizationAssignment", "roleAssignment", "roleSuffix"]

    @field_validator('provider_type')
    def provider_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['k8s']):
            raise ValueError("must be one of enum values ('k8s')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of K8sProviderSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organization_assignment
        if self.organization_assignment:
            _dict['organizationAssignment'] = self.organization_assignment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of role_assignment
        if self.role_assignment:
            _dict['roleAssignment'] = self.role_assignment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of K8sProviderSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "providerType": obj.get("providerType"),
            "displayName": obj.get("displayName"),
            "apiUrl": obj.get("apiUrl"),
            "rbacNs": obj.get("rbacNs"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "organizationAssignment": AuthOrganizationAssignment.from_dict(obj["organizationAssignment"]) if obj.get("organizationAssignment") is not None else None,
            "roleAssignment": AuthRoleAssignment.from_dict(obj["roleAssignment"]) if obj.get("roleAssignment") is not None else None,
            "roleSuffix": obj.get("roleSuffix")
        })
        return _obj


