# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from flightctl.models.git_hub_introspection_spec import GitHubIntrospectionSpec
from flightctl.models.jwt_introspection_spec import JwtIntrospectionSpec
from flightctl.models.rfc7662_introspection_spec import Rfc7662IntrospectionSpec
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

OAUTH2INTROSPECTION_ONE_OF_SCHEMAS = ["GitHubIntrospectionSpec", "JwtIntrospectionSpec", "Rfc7662IntrospectionSpec"]

class OAuth2Introspection(BaseModel):
    """
    OAuth2Introspection defines the token introspection configuration.
    """
    # data type: Rfc7662IntrospectionSpec
    oneof_schema_1_validator: Optional[Rfc7662IntrospectionSpec] = None
    # data type: GitHubIntrospectionSpec
    oneof_schema_2_validator: Optional[GitHubIntrospectionSpec] = None
    # data type: JwtIntrospectionSpec
    oneof_schema_3_validator: Optional[JwtIntrospectionSpec] = None
    actual_instance: Optional[Union[GitHubIntrospectionSpec, JwtIntrospectionSpec, Rfc7662IntrospectionSpec]] = None
    one_of_schemas: Set[str] = { "GitHubIntrospectionSpec", "JwtIntrospectionSpec", "Rfc7662IntrospectionSpec" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = OAuth2Introspection.model_construct()
        error_messages = []
        match = 0
        # validate data type: Rfc7662IntrospectionSpec
        if not isinstance(v, Rfc7662IntrospectionSpec):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Rfc7662IntrospectionSpec`")
        else:
            match += 1
        # validate data type: GitHubIntrospectionSpec
        if not isinstance(v, GitHubIntrospectionSpec):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GitHubIntrospectionSpec`")
        else:
            match += 1
        # validate data type: JwtIntrospectionSpec
        if not isinstance(v, JwtIntrospectionSpec):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JwtIntrospectionSpec`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OAuth2Introspection with oneOf schemas: GitHubIntrospectionSpec, JwtIntrospectionSpec, Rfc7662IntrospectionSpec. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OAuth2Introspection with oneOf schemas: GitHubIntrospectionSpec, JwtIntrospectionSpec, Rfc7662IntrospectionSpec. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("type")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `type` in the input.")

        # check if data type is `GitHubIntrospectionSpec`
        if _data_type == "github":
            instance.actual_instance = GitHubIntrospectionSpec.from_json(json_str)
            return instance

        # check if data type is `JwtIntrospectionSpec`
        if _data_type == "jwt":
            instance.actual_instance = JwtIntrospectionSpec.from_json(json_str)
            return instance

        # check if data type is `Rfc7662IntrospectionSpec`
        if _data_type == "rfc7662":
            instance.actual_instance = Rfc7662IntrospectionSpec.from_json(json_str)
            return instance

        # deserialize data into Rfc7662IntrospectionSpec
        try:
            instance.actual_instance = Rfc7662IntrospectionSpec.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GitHubIntrospectionSpec
        try:
            instance.actual_instance = GitHubIntrospectionSpec.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JwtIntrospectionSpec
        try:
            instance.actual_instance = JwtIntrospectionSpec.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into OAuth2Introspection with oneOf schemas: GitHubIntrospectionSpec, JwtIntrospectionSpec, Rfc7662IntrospectionSpec. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OAuth2Introspection with oneOf schemas: GitHubIntrospectionSpec, JwtIntrospectionSpec, Rfc7662IntrospectionSpec. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GitHubIntrospectionSpec, JwtIntrospectionSpec, Rfc7662IntrospectionSpec]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


