# coding: utf-8

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from flightctl.models.systemd_active_state_type import SystemdActiveStateType
from flightctl.models.systemd_enable_state_type import SystemdEnableStateType
from flightctl.models.systemd_load_state_type import SystemdLoadStateType
from typing import Optional, Set
from typing_extensions import Self

class SystemdUnitStatus(BaseModel):
    """
    SystemdUnitStatus
    """ # noqa: E501
    unit: StrictStr = Field(description="The unit name (e.g., \"sshd.service\").")
    description: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="The human-readable description for the unit.")
    enable_state: SystemdEnableStateType = Field(alias="enableState")
    load_state: SystemdLoadStateType = Field(alias="loadState")
    active_state: SystemdActiveStateType = Field(alias="activeState")
    sub_state: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The low-level, unit-type-specific state.", alias="subState")
    __properties: ClassVar[List[str]] = ["unit", "description", "enableState", "loadState", "activeState", "subState"]

    @field_validator('sub_state')
    def sub_state_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9-]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9-]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemdUnitStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemdUnitStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unit": obj.get("unit"),
            "description": obj.get("description"),
            "enableState": obj.get("enableState"),
            "loadState": obj.get("loadState"),
            "activeState": obj.get("activeState"),
            "subState": obj.get("subState")
        })
        return _obj


