# coding: utf-8

# flake8: noqa

"""
    Flight Control API

    [Flight Control](https://flightctl.io) is a service for declarative management of fleets of edge devices and their workloads. 

    The version of the OpenAPI document: v1beta1
    Contact: team@flightctl.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "AuthproviderApi",
    "CertificatesigningrequestApi",
    "DeviceApi",
    "DeviceactionsApi",
    "EnrollmentrequestApi",
    "EventApi",
    "FleetApi",
    "LabelApi",
    "OrganizationApi",
    "RepositoryApi",
    "ResourcesyncApi",
    "VersionApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AapProviderSpec",
    "AbsolutePath",
    "AppType",
    "ApplicationContent",
    "ApplicationEnvVars",
    "ApplicationProviderSpec",
    "ApplicationResourceLimits",
    "ApplicationResources",
    "ApplicationStatusType",
    "ApplicationVolume",
    "ApplicationVolumeProviderSpec",
    "ApplicationVolumeReclaimPolicy",
    "ApplicationVolumeStatus",
    "ApplicationsSummaryStatusType",
    "AuthConfig",
    "AuthDynamicOrganizationAssignment",
    "AuthDynamicRoleAssignment",
    "AuthOrganizationAssignment",
    "AuthPerUserOrganizationAssignment",
    "AuthProvider",
    "AuthProviderList",
    "AuthProviderSpec",
    "AuthRoleAssignment",
    "AuthStaticOrganizationAssignment",
    "AuthStaticRoleAssignment",
    "Batch",
    "BatchLimit",
    "BatchSequence",
    "CertificateSigningRequest",
    "CertificateSigningRequestList",
    "CertificateSigningRequestSpec",
    "CertificateSigningRequestStatus",
    "Condition",
    "ConditionStatus",
    "ConditionType",
    "ConfigProviderSpec",
    "CpuResourceMonitorSpec",
    "Device",
    "DeviceApplicationStatus",
    "DeviceApplicationsSummaryStatus",
    "DeviceConfigStatus",
    "DeviceConsole",
    "DeviceDecommission",
    "DeviceDecommissionTargetType",
    "DeviceIntegrityCheckStatus",
    "DeviceIntegrityCheckStatusType",
    "DeviceIntegrityStatus",
    "DeviceIntegrityStatusSummaryType",
    "DeviceLastSeen",
    "DeviceLifecycleHookType",
    "DeviceLifecycleStatus",
    "DeviceLifecycleStatusType",
    "DeviceList",
    "DeviceMultipleOwnersDetectedDetails",
    "DeviceMultipleOwnersResolvedDetails",
    "DeviceOsSpec",
    "DeviceOsStatus",
    "DeviceOwnershipChangedDetails",
    "DeviceResourceStatus",
    "DeviceResourceStatusType",
    "DeviceResumeRequest",
    "DeviceResumeResponse",
    "DeviceSpec",
    "DeviceSpecSystemd",
    "DeviceStatus",
    "DeviceSummaryStatus",
    "DeviceSummaryStatusType",
    "DeviceSystemInfo",
    "DeviceUpdatePolicySpec",
    "DeviceUpdatedStatus",
    "DeviceUpdatedStatusType",
    "DevicesSummary",
    "DiskResourceMonitorSpec",
    "DisruptionBudget",
    "EncodingType",
    "EnrollmentConfig",
    "EnrollmentRequest",
    "EnrollmentRequestApproval",
    "EnrollmentRequestApprovalStatus",
    "EnrollmentRequestList",
    "EnrollmentRequestSpec",
    "EnrollmentRequestStatus",
    "EnrollmentService",
    "EnrollmentServiceAuth",
    "EnrollmentServiceService",
    "Event",
    "EventDetails",
    "EventList",
    "EventSource",
    "FileContent",
    "FileMetadata",
    "FileOperation",
    "FileSpec",
    "Fleet",
    "FleetList",
    "FleetRolloutBatchCompletedDetails",
    "FleetRolloutBatchDispatchedDetails",
    "FleetRolloutCompletedDetails",
    "FleetRolloutDeviceSelectedDetails",
    "FleetRolloutFailedDetails",
    "FleetRolloutStartedDetails",
    "FleetRolloutStatus",
    "FleetSpec",
    "FleetSpecTemplate",
    "FleetStatus",
    "GenericRepoSpec",
    "GitConfigProviderSpec",
    "GitConfigProviderSpecGitRef",
    "GitHubIntrospectionSpec",
    "HookAction",
    "HookActionRun",
    "HookCondition",
    "HookConditionPathOp",
    "HttpConfig",
    "HttpConfigProviderSpec",
    "HttpConfigProviderSpecHttpRef",
    "HttpRepoSpec",
    "ImageApplicationProviderSpec",
    "ImageMountVolumeProviderSpec",
    "ImagePullPolicy",
    "ImageVolumeProviderSpec",
    "ImageVolumeSource",
    "InlineApplicationProviderSpec",
    "InlineConfigProviderSpec",
    "InternalTaskFailedDetails",
    "InternalTaskPermanentlyFailedDetails",
    "JwtIntrospectionSpec",
    "K8sProviderSpec",
    "KubernetesSecretProviderSpec",
    "KubernetesSecretProviderSpecSecretRef",
    "LabelSelector",
    "ListMeta",
    "MatchExpression",
    "MemoryResourceMonitorSpec",
    "MountVolumeProviderSpec",
    "OAuth2Introspection",
    "OAuth2ProviderSpec",
    "OIDCProviderSpec",
    "ObjectMeta",
    "ObjectReference",
    "OpenShiftProviderSpec",
    "Organization",
    "OrganizationList",
    "OrganizationSpec",
    "PatchRequestInner",
    "Permission",
    "PermissionList",
    "ReferencedRepositoryUpdatedDetails",
    "RelativePath",
    "RepoSpecType",
    "Repository",
    "RepositoryList",
    "RepositorySpec",
    "RepositoryStatus",
    "ResourceAlertRule",
    "ResourceAlertSeverityType",
    "ResourceKind",
    "ResourceMonitor",
    "ResourceMonitorSpec",
    "ResourceSync",
    "ResourceSyncCompletedDetails",
    "ResourceSyncList",
    "ResourceSyncSpec",
    "ResourceSyncStatus",
    "ResourceUpdatedDetails",
    "Rfc7662IntrospectionSpec",
    "RolloutPolicy",
    "RolloutStrategy",
    "SshConfig",
    "SshRepoSpec",
    "Status",
    "SystemdActiveStateType",
    "SystemdEnableStateType",
    "SystemdLoadStateType",
    "SystemdUnitStatus",
    "TemplateVersion",
    "TemplateVersionList",
    "TemplateVersionSpec",
    "TemplateVersionStatus",
    "TokenRequest",
    "TokenResponse",
    "UpdateSchedule",
    "UserInfoResponse",
    "Version",
    "VolumeMount",
]

# import apis into sdk package
from flightctl.api.authentication_api import AuthenticationApi as AuthenticationApi
from flightctl.api.authprovider_api import AuthproviderApi as AuthproviderApi
from flightctl.api.certificatesigningrequest_api import CertificatesigningrequestApi as CertificatesigningrequestApi
from flightctl.api.device_api import DeviceApi as DeviceApi
from flightctl.api.deviceactions_api import DeviceactionsApi as DeviceactionsApi
from flightctl.api.enrollmentrequest_api import EnrollmentrequestApi as EnrollmentrequestApi
from flightctl.api.event_api import EventApi as EventApi
from flightctl.api.fleet_api import FleetApi as FleetApi
from flightctl.api.label_api import LabelApi as LabelApi
from flightctl.api.organization_api import OrganizationApi as OrganizationApi
from flightctl.api.repository_api import RepositoryApi as RepositoryApi
from flightctl.api.resourcesync_api import ResourcesyncApi as ResourcesyncApi
from flightctl.api.version_api import VersionApi as VersionApi

# import ApiClient
from flightctl.api_response import ApiResponse as ApiResponse
from flightctl.api_client import ApiClient as ApiClient
from flightctl.configuration import Configuration as Configuration
from flightctl.exceptions import OpenApiException as OpenApiException
from flightctl.exceptions import ApiTypeError as ApiTypeError
from flightctl.exceptions import ApiValueError as ApiValueError
from flightctl.exceptions import ApiKeyError as ApiKeyError
from flightctl.exceptions import ApiAttributeError as ApiAttributeError
from flightctl.exceptions import ApiException as ApiException

# import models into sdk package
from flightctl.models.aap_provider_spec import AapProviderSpec as AapProviderSpec
from flightctl.models.absolute_path import AbsolutePath as AbsolutePath
from flightctl.models.app_type import AppType as AppType
from flightctl.models.application_content import ApplicationContent as ApplicationContent
from flightctl.models.application_env_vars import ApplicationEnvVars as ApplicationEnvVars
from flightctl.models.application_provider_spec import ApplicationProviderSpec as ApplicationProviderSpec
from flightctl.models.application_resource_limits import ApplicationResourceLimits as ApplicationResourceLimits
from flightctl.models.application_resources import ApplicationResources as ApplicationResources
from flightctl.models.application_status_type import ApplicationStatusType as ApplicationStatusType
from flightctl.models.application_volume import ApplicationVolume as ApplicationVolume
from flightctl.models.application_volume_provider_spec import ApplicationVolumeProviderSpec as ApplicationVolumeProviderSpec
from flightctl.models.application_volume_reclaim_policy import ApplicationVolumeReclaimPolicy as ApplicationVolumeReclaimPolicy
from flightctl.models.application_volume_status import ApplicationVolumeStatus as ApplicationVolumeStatus
from flightctl.models.applications_summary_status_type import ApplicationsSummaryStatusType as ApplicationsSummaryStatusType
from flightctl.models.auth_config import AuthConfig as AuthConfig
from flightctl.models.auth_dynamic_organization_assignment import AuthDynamicOrganizationAssignment as AuthDynamicOrganizationAssignment
from flightctl.models.auth_dynamic_role_assignment import AuthDynamicRoleAssignment as AuthDynamicRoleAssignment
from flightctl.models.auth_organization_assignment import AuthOrganizationAssignment as AuthOrganizationAssignment
from flightctl.models.auth_per_user_organization_assignment import AuthPerUserOrganizationAssignment as AuthPerUserOrganizationAssignment
from flightctl.models.auth_provider import AuthProvider as AuthProvider
from flightctl.models.auth_provider_list import AuthProviderList as AuthProviderList
from flightctl.models.auth_provider_spec import AuthProviderSpec as AuthProviderSpec
from flightctl.models.auth_role_assignment import AuthRoleAssignment as AuthRoleAssignment
from flightctl.models.auth_static_organization_assignment import AuthStaticOrganizationAssignment as AuthStaticOrganizationAssignment
from flightctl.models.auth_static_role_assignment import AuthStaticRoleAssignment as AuthStaticRoleAssignment
from flightctl.models.batch import Batch as Batch
from flightctl.models.batch_limit import BatchLimit as BatchLimit
from flightctl.models.batch_sequence import BatchSequence as BatchSequence
from flightctl.models.certificate_signing_request import CertificateSigningRequest as CertificateSigningRequest
from flightctl.models.certificate_signing_request_list import CertificateSigningRequestList as CertificateSigningRequestList
from flightctl.models.certificate_signing_request_spec import CertificateSigningRequestSpec as CertificateSigningRequestSpec
from flightctl.models.certificate_signing_request_status import CertificateSigningRequestStatus as CertificateSigningRequestStatus
from flightctl.models.condition import Condition as Condition
from flightctl.models.condition_status import ConditionStatus as ConditionStatus
from flightctl.models.condition_type import ConditionType as ConditionType
from flightctl.models.config_provider_spec import ConfigProviderSpec as ConfigProviderSpec
from flightctl.models.cpu_resource_monitor_spec import CpuResourceMonitorSpec as CpuResourceMonitorSpec
from flightctl.models.device import Device as Device
from flightctl.models.device_application_status import DeviceApplicationStatus as DeviceApplicationStatus
from flightctl.models.device_applications_summary_status import DeviceApplicationsSummaryStatus as DeviceApplicationsSummaryStatus
from flightctl.models.device_config_status import DeviceConfigStatus as DeviceConfigStatus
from flightctl.models.device_console import DeviceConsole as DeviceConsole
from flightctl.models.device_decommission import DeviceDecommission as DeviceDecommission
from flightctl.models.device_decommission_target_type import DeviceDecommissionTargetType as DeviceDecommissionTargetType
from flightctl.models.device_integrity_check_status import DeviceIntegrityCheckStatus as DeviceIntegrityCheckStatus
from flightctl.models.device_integrity_check_status_type import DeviceIntegrityCheckStatusType as DeviceIntegrityCheckStatusType
from flightctl.models.device_integrity_status import DeviceIntegrityStatus as DeviceIntegrityStatus
from flightctl.models.device_integrity_status_summary_type import DeviceIntegrityStatusSummaryType as DeviceIntegrityStatusSummaryType
from flightctl.models.device_last_seen import DeviceLastSeen as DeviceLastSeen
from flightctl.models.device_lifecycle_hook_type import DeviceLifecycleHookType as DeviceLifecycleHookType
from flightctl.models.device_lifecycle_status import DeviceLifecycleStatus as DeviceLifecycleStatus
from flightctl.models.device_lifecycle_status_type import DeviceLifecycleStatusType as DeviceLifecycleStatusType
from flightctl.models.device_list import DeviceList as DeviceList
from flightctl.models.device_multiple_owners_detected_details import DeviceMultipleOwnersDetectedDetails as DeviceMultipleOwnersDetectedDetails
from flightctl.models.device_multiple_owners_resolved_details import DeviceMultipleOwnersResolvedDetails as DeviceMultipleOwnersResolvedDetails
from flightctl.models.device_os_spec import DeviceOsSpec as DeviceOsSpec
from flightctl.models.device_os_status import DeviceOsStatus as DeviceOsStatus
from flightctl.models.device_ownership_changed_details import DeviceOwnershipChangedDetails as DeviceOwnershipChangedDetails
from flightctl.models.device_resource_status import DeviceResourceStatus as DeviceResourceStatus
from flightctl.models.device_resource_status_type import DeviceResourceStatusType as DeviceResourceStatusType
from flightctl.models.device_resume_request import DeviceResumeRequest as DeviceResumeRequest
from flightctl.models.device_resume_response import DeviceResumeResponse as DeviceResumeResponse
from flightctl.models.device_spec import DeviceSpec as DeviceSpec
from flightctl.models.device_spec_systemd import DeviceSpecSystemd as DeviceSpecSystemd
from flightctl.models.device_status import DeviceStatus as DeviceStatus
from flightctl.models.device_summary_status import DeviceSummaryStatus as DeviceSummaryStatus
from flightctl.models.device_summary_status_type import DeviceSummaryStatusType as DeviceSummaryStatusType
from flightctl.models.device_system_info import DeviceSystemInfo as DeviceSystemInfo
from flightctl.models.device_update_policy_spec import DeviceUpdatePolicySpec as DeviceUpdatePolicySpec
from flightctl.models.device_updated_status import DeviceUpdatedStatus as DeviceUpdatedStatus
from flightctl.models.device_updated_status_type import DeviceUpdatedStatusType as DeviceUpdatedStatusType
from flightctl.models.devices_summary import DevicesSummary as DevicesSummary
from flightctl.models.disk_resource_monitor_spec import DiskResourceMonitorSpec as DiskResourceMonitorSpec
from flightctl.models.disruption_budget import DisruptionBudget as DisruptionBudget
from flightctl.models.encoding_type import EncodingType as EncodingType
from flightctl.models.enrollment_config import EnrollmentConfig as EnrollmentConfig
from flightctl.models.enrollment_request import EnrollmentRequest as EnrollmentRequest
from flightctl.models.enrollment_request_approval import EnrollmentRequestApproval as EnrollmentRequestApproval
from flightctl.models.enrollment_request_approval_status import EnrollmentRequestApprovalStatus as EnrollmentRequestApprovalStatus
from flightctl.models.enrollment_request_list import EnrollmentRequestList as EnrollmentRequestList
from flightctl.models.enrollment_request_spec import EnrollmentRequestSpec as EnrollmentRequestSpec
from flightctl.models.enrollment_request_status import EnrollmentRequestStatus as EnrollmentRequestStatus
from flightctl.models.enrollment_service import EnrollmentService as EnrollmentService
from flightctl.models.enrollment_service_auth import EnrollmentServiceAuth as EnrollmentServiceAuth
from flightctl.models.enrollment_service_service import EnrollmentServiceService as EnrollmentServiceService
from flightctl.models.event import Event as Event
from flightctl.models.event_details import EventDetails as EventDetails
from flightctl.models.event_list import EventList as EventList
from flightctl.models.event_source import EventSource as EventSource
from flightctl.models.file_content import FileContent as FileContent
from flightctl.models.file_metadata import FileMetadata as FileMetadata
from flightctl.models.file_operation import FileOperation as FileOperation
from flightctl.models.file_spec import FileSpec as FileSpec
from flightctl.models.fleet import Fleet as Fleet
from flightctl.models.fleet_list import FleetList as FleetList
from flightctl.models.fleet_rollout_batch_completed_details import FleetRolloutBatchCompletedDetails as FleetRolloutBatchCompletedDetails
from flightctl.models.fleet_rollout_batch_dispatched_details import FleetRolloutBatchDispatchedDetails as FleetRolloutBatchDispatchedDetails
from flightctl.models.fleet_rollout_completed_details import FleetRolloutCompletedDetails as FleetRolloutCompletedDetails
from flightctl.models.fleet_rollout_device_selected_details import FleetRolloutDeviceSelectedDetails as FleetRolloutDeviceSelectedDetails
from flightctl.models.fleet_rollout_failed_details import FleetRolloutFailedDetails as FleetRolloutFailedDetails
from flightctl.models.fleet_rollout_started_details import FleetRolloutStartedDetails as FleetRolloutStartedDetails
from flightctl.models.fleet_rollout_status import FleetRolloutStatus as FleetRolloutStatus
from flightctl.models.fleet_spec import FleetSpec as FleetSpec
from flightctl.models.fleet_spec_template import FleetSpecTemplate as FleetSpecTemplate
from flightctl.models.fleet_status import FleetStatus as FleetStatus
from flightctl.models.generic_repo_spec import GenericRepoSpec as GenericRepoSpec
from flightctl.models.git_config_provider_spec import GitConfigProviderSpec as GitConfigProviderSpec
from flightctl.models.git_config_provider_spec_git_ref import GitConfigProviderSpecGitRef as GitConfigProviderSpecGitRef
from flightctl.models.git_hub_introspection_spec import GitHubIntrospectionSpec as GitHubIntrospectionSpec
from flightctl.models.hook_action import HookAction as HookAction
from flightctl.models.hook_action_run import HookActionRun as HookActionRun
from flightctl.models.hook_condition import HookCondition as HookCondition
from flightctl.models.hook_condition_path_op import HookConditionPathOp as HookConditionPathOp
from flightctl.models.http_config import HttpConfig as HttpConfig
from flightctl.models.http_config_provider_spec import HttpConfigProviderSpec as HttpConfigProviderSpec
from flightctl.models.http_config_provider_spec_http_ref import HttpConfigProviderSpecHttpRef as HttpConfigProviderSpecHttpRef
from flightctl.models.http_repo_spec import HttpRepoSpec as HttpRepoSpec
from flightctl.models.image_application_provider_spec import ImageApplicationProviderSpec as ImageApplicationProviderSpec
from flightctl.models.image_mount_volume_provider_spec import ImageMountVolumeProviderSpec as ImageMountVolumeProviderSpec
from flightctl.models.image_pull_policy import ImagePullPolicy as ImagePullPolicy
from flightctl.models.image_volume_provider_spec import ImageVolumeProviderSpec as ImageVolumeProviderSpec
from flightctl.models.image_volume_source import ImageVolumeSource as ImageVolumeSource
from flightctl.models.inline_application_provider_spec import InlineApplicationProviderSpec as InlineApplicationProviderSpec
from flightctl.models.inline_config_provider_spec import InlineConfigProviderSpec as InlineConfigProviderSpec
from flightctl.models.internal_task_failed_details import InternalTaskFailedDetails as InternalTaskFailedDetails
from flightctl.models.internal_task_permanently_failed_details import InternalTaskPermanentlyFailedDetails as InternalTaskPermanentlyFailedDetails
from flightctl.models.jwt_introspection_spec import JwtIntrospectionSpec as JwtIntrospectionSpec
from flightctl.models.k8s_provider_spec import K8sProviderSpec as K8sProviderSpec
from flightctl.models.kubernetes_secret_provider_spec import KubernetesSecretProviderSpec as KubernetesSecretProviderSpec
from flightctl.models.kubernetes_secret_provider_spec_secret_ref import KubernetesSecretProviderSpecSecretRef as KubernetesSecretProviderSpecSecretRef
from flightctl.models.label_selector import LabelSelector as LabelSelector
from flightctl.models.list_meta import ListMeta as ListMeta
from flightctl.models.match_expression import MatchExpression as MatchExpression
from flightctl.models.memory_resource_monitor_spec import MemoryResourceMonitorSpec as MemoryResourceMonitorSpec
from flightctl.models.mount_volume_provider_spec import MountVolumeProviderSpec as MountVolumeProviderSpec
from flightctl.models.o_auth2_introspection import OAuth2Introspection as OAuth2Introspection
from flightctl.models.o_auth2_provider_spec import OAuth2ProviderSpec as OAuth2ProviderSpec
from flightctl.models.oidc_provider_spec import OIDCProviderSpec as OIDCProviderSpec
from flightctl.models.object_meta import ObjectMeta as ObjectMeta
from flightctl.models.object_reference import ObjectReference as ObjectReference
from flightctl.models.open_shift_provider_spec import OpenShiftProviderSpec as OpenShiftProviderSpec
from flightctl.models.organization import Organization as Organization
from flightctl.models.organization_list import OrganizationList as OrganizationList
from flightctl.models.organization_spec import OrganizationSpec as OrganizationSpec
from flightctl.models.patch_request_inner import PatchRequestInner as PatchRequestInner
from flightctl.models.permission import Permission as Permission
from flightctl.models.permission_list import PermissionList as PermissionList
from flightctl.models.referenced_repository_updated_details import ReferencedRepositoryUpdatedDetails as ReferencedRepositoryUpdatedDetails
from flightctl.models.relative_path import RelativePath as RelativePath
from flightctl.models.repo_spec_type import RepoSpecType as RepoSpecType
from flightctl.models.repository import Repository as Repository
from flightctl.models.repository_list import RepositoryList as RepositoryList
from flightctl.models.repository_spec import RepositorySpec as RepositorySpec
from flightctl.models.repository_status import RepositoryStatus as RepositoryStatus
from flightctl.models.resource_alert_rule import ResourceAlertRule as ResourceAlertRule
from flightctl.models.resource_alert_severity_type import ResourceAlertSeverityType as ResourceAlertSeverityType
from flightctl.models.resource_kind import ResourceKind as ResourceKind
from flightctl.models.resource_monitor import ResourceMonitor as ResourceMonitor
from flightctl.models.resource_monitor_spec import ResourceMonitorSpec as ResourceMonitorSpec
from flightctl.models.resource_sync import ResourceSync as ResourceSync
from flightctl.models.resource_sync_completed_details import ResourceSyncCompletedDetails as ResourceSyncCompletedDetails
from flightctl.models.resource_sync_list import ResourceSyncList as ResourceSyncList
from flightctl.models.resource_sync_spec import ResourceSyncSpec as ResourceSyncSpec
from flightctl.models.resource_sync_status import ResourceSyncStatus as ResourceSyncStatus
from flightctl.models.resource_updated_details import ResourceUpdatedDetails as ResourceUpdatedDetails
from flightctl.models.rfc7662_introspection_spec import Rfc7662IntrospectionSpec as Rfc7662IntrospectionSpec
from flightctl.models.rollout_policy import RolloutPolicy as RolloutPolicy
from flightctl.models.rollout_strategy import RolloutStrategy as RolloutStrategy
from flightctl.models.ssh_config import SshConfig as SshConfig
from flightctl.models.ssh_repo_spec import SshRepoSpec as SshRepoSpec
from flightctl.models.status import Status as Status
from flightctl.models.systemd_active_state_type import SystemdActiveStateType as SystemdActiveStateType
from flightctl.models.systemd_enable_state_type import SystemdEnableStateType as SystemdEnableStateType
from flightctl.models.systemd_load_state_type import SystemdLoadStateType as SystemdLoadStateType
from flightctl.models.systemd_unit_status import SystemdUnitStatus as SystemdUnitStatus
from flightctl.models.template_version import TemplateVersion as TemplateVersion
from flightctl.models.template_version_list import TemplateVersionList as TemplateVersionList
from flightctl.models.template_version_spec import TemplateVersionSpec as TemplateVersionSpec
from flightctl.models.template_version_status import TemplateVersionStatus as TemplateVersionStatus
from flightctl.models.token_request import TokenRequest as TokenRequest
from flightctl.models.token_response import TokenResponse as TokenResponse
from flightctl.models.update_schedule import UpdateSchedule as UpdateSchedule
from flightctl.models.user_info_response import UserInfoResponse as UserInfoResponse
from flightctl.models.version import Version as Version
from flightctl.models.volume_mount import VolumeMount as VolumeMount

